# Projektinformationen
site_name: 'Aljoshas Documentation'
site_url: 'https://docs.aljosha.eu/'
site_description: 'Documentation of some projects of Aljosha'
site_author: Aljosha
site_dir: /home/users/aljosha/www/docs

# Repoinformationen
repo_name: CraftTopia/wiki
repo_url: 'https://github.com/AljoshaVieth/Documentations'
edit_uri: 'blob/main/docs/'
edit_uri_template: '-/sse/master/docs%2F{path!q}'

# Copyrightinfo
copyright: '&copy; 2022 Aljosha'

# Konfigurationen
theme:
  name: material
  language: de
  palette:
    scheme: slate
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /img/favicon.ico

# sonstiges
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://www.crafttopia.de
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AljoshaVieth

plugins:
  - search # erforderlich, damit die Suche funktioniert
  #- git-revision-date-localized # Datum der letzten Änderung am Ende der Seite
  - awesome-pages # benutzerdefinierte Navigationsanordnung
      
nav:
    - Portal: https://CraftTopia.de/
    - Discord: http://discord.crafttopia.de/
    - Shop: http://shop.crafttopia.net/
    - Vote: https://CraftTopia.de/vote
    - Status: https://CraftTopia.de/status

